name: Deploy Memory Game

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Clone repository
      uses: actions/checkout@v3

    - name: ✅ Check index.html exists
      run: |
        if [ ! -f "index.html" ]; then
          echo "index.html not found!"
          exit 1
        fi
        echo "index.html found ✅"

    - name: 🚀 Deployment complete
      run: echo "Ready to deploy!"
